include:
  - board: seeeduino_xiao_ble
    shield: chippy_left
  - board: seeeduino_xiao_ble
    shield: chippy_right

  - board: nice_nano_v2
    shield: chipper_dongle_nano dongle_display 
  - board: seeeduino_xiao_ble
    shield: chipper_dongle_xiao dongle_display
  - board: seeeduino_xiao_ble
    shield: chipper_left rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: chipper_peripheral_left rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: chipper_right rgbled_adapter

  - board: seeeduino_xiao_ble
    shield: totem_left rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: totem_right rgbled_adapter

  - board: nice_nano_v2 
    shield: corne_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view

  - shield: settings_reset
    board: seeeduino_xiao_ble
  - board: nice_nano_v2
    shield: settings_reset
