include:
  - board: seeeduino_xiao_ble
    shield: chippy_left
  - board: seeeduino_xiao_ble
    shield: chippy_right

  - board: seeeduino_xiao_ble
    shield: chipper_dongle_xiao dongle_display
  - board: seeeduino_xiao_ble
    shield: chipper_left rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: chipper_peripheral_left rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: chipper_right rgbled_adapter

  - shield: settings_reset
    board: seeeduino_xiao_ble
