include:
  - board: seeeduino_xiao_ble
    shield: chippy_left rgbled_adapter nice_view_adapter nice_view_gem
  - board: seeeduino_xiao_ble
    shield: chippy_right rgbled_adapter nice_view_adapter nice_view_gem

  - shield: settings_reset
    board: seeeduino_xiao_ble
