include:
  - board: seeeduino_xiao_ble
    shield: chippy_left
  - board: seeeduino_xiao_ble
    shield: chippy_right

  - board: seeeduino_xiao_ble
    shield: chipper_dongle_xiao dongle_display
  - board: seeeduino_xiao_ble
    shield: chipper_left
  - board: seeeduino_xiao_ble
    shield: chipper_peripheral_left
  - board: seeeduino_xiao_ble
    shield: chipper_right

  - shield: settings_reset
    board: seeeduino_xiao_ble
